#include <cassert>
#include <string>

#include <gungnir/database/database.hpp>
#include <gungnir/migration/migration.hpp>

class CreateUsersTable : public gungnir::Migration {
public:
    void up() override {
        Table::create("users", [](Column& column) {
            column.id();
            column.uuid("public_id").unique();
            column.string("email").unique();
            column.boolean("active").default_value(true);
            column.enumeration("status", {"active", "disabled"})
                .default_value("active");
            column.json("profile").nullable();
            column.foreign_id("role_id")
                .constrained("roles")
                .cascade_on_delete();
            column.timestamps();

            column.index({"active", "status"}, "users_active_status_index");
        });
    }

    void down() override {
        Table::drop_if_exists("users");
    }
};

bool contains(
    const gungnir::database::Compilation& compilation,
    const std::string& text
) {
    for (const auto& statement : compilation.statements) {
        if (statement.text.find(text) != std::string::npos) {
            return true;
        }
    }
    return false;
}

int main() {
    CreateUsersTable migration;
    const auto plan = migration.plan_up();

    const auto postgres = gungnir::database::compile(
        plan,
        gungnir::database::Backend::postgresql
    );
    assert(!postgres.empty());
    assert(contains(postgres, "CREATE TABLE \"users\""));
    assert(contains(postgres, "GENERATED BY DEFAULT AS IDENTITY"));
    assert(contains(postgres, "JSONB"));
    assert(contains(postgres, "CREATE INDEX \"users_active_status_index\""));

    const auto mysql = gungnir::database::compile(
        plan,
        gungnir::database::Backend::mysql
    );
    assert(!mysql.empty());
    assert(contains(mysql, "CREATE TABLE `users`"));
    assert(contains(mysql, "AUTO_INCREMENT"));
    assert(contains(mysql, "ENUM('active', 'disabled')"));
    assert(contains(mysql, "JSON"));

    const auto mssql = gungnir::database::compile(
        plan,
        gungnir::database::Backend::mssql
    );
    assert(!mssql.empty());
    assert(contains(mssql, "CREATE TABLE [users]"));
    assert(contains(mssql, "IDENTITY(1,1)"));
    assert(contains(mssql, "UNIQUEIDENTIFIER"));
    assert(contains(mssql, "ISJSON([profile])"));

    const auto mongodb = gungnir::database::compile(
        plan,
        gungnir::database::Backend::mongodb
    );
    assert(!mongodb.empty());
    assert(
        mongodb.statements.front().kind ==
        gungnir::database::StatementKind::mongodb_command
    );
    assert(contains(mongodb, "\"create\":\"users\""));
    assert(contains(mongodb, "\"createIndexes\":\"users\""));
    assert(mongodb.has_warnings());

    return 0;
}
