#include <cassert>
#include <cstdlib>
#include <memory>
#include <string>

#include <gungnir/database/database.hpp>
#include <gungnir/database/postgresql.hpp>

namespace {

gungnir::String env(
    const char* name,
    gungnir::String fallback
) {
    const auto* value =
        std::getenv(name);

    return
        value == nullptr
            ? std::move(fallback)
            : gungnir::String{value};
}

std::uint16_t port() {
    const auto value =
        env(
            "GUNGNIR_POSTGRESQL_PORT",
            "5432"
        );

    return static_cast<std::uint16_t>(
        std::stoul(value)
    );
}

} // namespace

int main() {
    using namespace gungnir;

    database::Settings settings;
    settings.name = "postgresql_integration";
    settings.backend =
        database::Backend::postgresql;
    settings.host =
        env(
            "GUNGNIR_POSTGRESQL_HOST",
            "127.0.0.1"
        );
    settings.port = port();
    settings.database =
        env(
            "GUNGNIR_POSTGRESQL_DATABASE",
            "gungnir"
        );
    settings.username =
        env(
            "GUNGNIR_POSTGRESQL_USERNAME",
            "postgres"
        );
    settings.password =
        env(
            "GUNGNIR_POSTGRESQL_PASSWORD",
            "postgres"
        );

    database::DriverRegistry registry;
    database::register_postgresql(
        registry
    );

    assert(
        registry.has(
            database::Backend::postgresql
        )
    );

    database::Manager manager;
    manager.add(
        settings.name,
        settings.backend,
        registry.bind(settings),
        2
    );

    auto connection =
        manager.connection(
            settings.name
        );

    assert(connection->healthy());

    connection->execute(
        "DROP TABLE IF EXISTS gungnir_postgresql_integration"
    );

    connection->execute(
        "CREATE TABLE gungnir_postgresql_integration ("
        "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
        "email TEXT NOT NULL UNIQUE,"
        "active BOOLEAN NOT NULL,"
        "score DOUBLE PRECISION NOT NULL,"
        "note TEXT NULL"
        ")"
    );

    const auto inserted =
        connection->execute(
            "INSERT INTO gungnir_postgresql_integration "
            "(email, active, score, note) "
            "VALUES ($1, $2, $3, $4) "
            "RETURNING id, email, active, score, note",
            {
                String{"first@example.com"},
                Boolean{true},
                Double{12.5},
                nullptr
            }
        );

    assert(inserted.affected_rows == 1);
    assert(inserted.rows.size() == 1);
    assert(inserted.inserted_id.has_value());

    const auto& first =
        inserted.rows.front();

    assert(
        model::value_cast<String>(
            first.at("email")
        ) ==
        "first@example.com"
    );

    assert(
        model::value_cast<Boolean>(
            first.at("active")
        )
    );

    assert(
        model::value_cast<Double>(
            first.at("score")
        ) ==
        12.5
    );

    assert(
        std::holds_alternative<
            std::nullptr_t
        >(
            first.at("note")
        )
    );

    connection->begin();

    connection->execute(
        "INSERT INTO gungnir_postgresql_integration "
        "(email, active, score, note) "
        "VALUES ($1, $2, $3, $4)",
        {
            String{"rolled-back@example.com"},
            Boolean{false},
            Double{1.0},
            String{"temporary"}
        }
    );

    connection->rollback();

    const auto rolled_back =
        connection->execute(
            "SELECT COUNT(*)::BIGINT AS count "
            "FROM gungnir_postgresql_integration "
            "WHERE email = $1",
            {
                String{
                    "rolled-back@example.com"
                }
            }
        );

    assert(
        model::value_cast<Int64>(
            rolled_back.rows.front().at(
                "count"
            )
        ) ==
        0
    );

    connection->begin();

    connection->execute(
        "INSERT INTO gungnir_postgresql_integration "
        "(email, active, score, note) "
        "VALUES ($1, $2, $3, $4)",
        {
            String{"committed@example.com"},
            Boolean{false},
            Double{4.25},
            String{"persisted"}
        }
    );

    connection->commit();

    const auto selected =
        connection->execute(
            "SELECT id, email, active, score, note "
            "FROM gungnir_postgresql_integration "
            "WHERE email = $1",
            {
                String{
                    "committed@example.com"
                }
            }
        );

    assert(selected.rows.size() == 1);
    assert(
        model::value_cast<String>(
            selected.rows.front().at(
                "note"
            )
        ) ==
        "persisted"
    );

    connection->execute(
        "DROP TABLE gungnir_postgresql_integration"
    );

    return 0;
}
